locale: "en-US"
title: Gustavo Walbon
url: "https://walbon.github.io/"
baseurl: ""
google_analytics_key: "UA-108695578-1"
comments: true
disqus-shortname: github-walbon
description: > # this means to ignore newlines until "baseurl:"
  Gustavo  Walbon writes somes articles to be share with you, enjoy them. :)

# Author details for the jekyll-seo-tag gem
author:
  name: Gustavo Walbon
  email: 
  twitter: gustavowalbon

permalink: pretty

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-sitemap"

